### PR TITLE
Dump latlon

### PR DESCRIPTION
**Pull request by jshipton**
This provides the option to dump fields on a latlon coordinate mesh. The user specifies fieldnames in  output.dumplist_latlon, which is set by default to be an empty list. This option has been added to the sw_williamson_triangle test but this test doesn't currently do anything more than set up the initial conditions.

Concerns:
- the dump method is becoming rather long - would it be a good idea to move the creation of the latlon mesh to another place?
- is there a way to check if the original mesh is actually a sphere?! (or is this overkill?)

### CODE REVIEW

**Comment by colinjcotter** [comment]
I don't think that there is any need to check if the original mesh is actually a sphere!

**Comment by colinjcotter** [comment]
I think that the lat-lon calculation should indeed be in a separate function.

**Comment by jshipton** [comment]
I think this is good to go...

**Comment by jshipton** [comment]
Test failure due to problem gunzipping h5py.tar.gz on travis. Merging.

**Pull request merged**
