### PR TITLE
Use preonly hybridization in the ShallowWaterSolver

### PR DESCRIPTION
**Pull request by thomasgibson**
This PR adds hybridization parameters for the shallow water solver.

### CODE REVIEW

**Comment by dorugeber** [comment]
I'm sort of wary of these parameters being copy-pasted into 4 examples.  Some better-sounding alternatives, other ideas welcome:
1) copy one example (e.g. Williamson 5) and make a new `sw_williamson5_hybridized.py` example
2) rename one of the current examples to `..._hybridized.py` and use this
3) presumably the current SW code uses some solver options (it's surely not the default GMRES/ILU, probably some Lawrence fieldsplit magic).  If these options are clearly better, why not replace the default options within Gusto?  (can always rip out the current options and use them in one example as a 'backup')

**Comment by thomasgibson** [comment]
I think 3 would be the cleanest way, as I don't want to bloat the examples code with even more duplication (unless people would rather have separate hybridization tests). Making the hybridization parameters default for the `ShallowWaterSolver` is an option.

**Comment by dorugeber** [comment]
Then you should get this past @jshipton and @colinjcotter!

**Comment by dorugeber** [comment]
What is the status of this?

**Comment by jshipton** [comment]
Final decision on solver parameters to be made by Colin (currently in Tuscany)

**Comment by jshipton** [comment]
I think this is now superseded by https://github.com/firedrakeproject/gusto/pull/131 - @thomasgibson, is that correct?

**Comment by thomasgibson** [comment]
Yes, we can close this.

**Pull request closed without merging**
