### PR TITLE
Move theta input and change error check

### PR DESCRIPTION
**Pull request by atb1995**
theta is changed from an optional argument in `ThetaMethod` to required and limited to `0 < theta < 1`. `ImplicitMidpoint` is changed to be called `TrapeziumRule`. Note, in future we could add the actual Implicit Method in future.

### CODE REVIEW

**Review by tommbendall — COMMENTED** [review]
The code changes are exactly right so as it stands this could be merged onto main. But...
1. Could you write a short description of the PR (under the "conversation" tab)
2. Do we want to think about renaming this? I've always wanted to clarify the difference between the following two schemes:
```
q^{n+1} = q^n + 0.5*dt*F(q^n) + 0.5*dt*F(q^{n+1})
```
and
```
q^{n+1} = q^n + dt*F(0.5*[q^n+q^{n+1}])
```
Since this one is the first, I had wondered if this should be called something like the `TrapezoidalThetaMethod`? What do you think?

**Comment by atb1995** [comment]
I've changed the name of ImplicitMidpoint

**Comment by tommbendall** [comment]
I'm afraid the branch is still failing! I also wondered if we should open an issue to implement `GeneralisedMidpoint` and `ImplicitMidpoint` discretisations?

**Comment by atb1995** [comment]
Yep I missed an `ImplicitMidpoint` and had some trailing whitespace! I think that would be good, although I think it will be tied in to having implicit multistage schemes with a butcher tableau (after explicit is done). I could still create an issue?

**Review by tommbendall — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
